Repository JNU-econovation/econo-overflow, pull requests merged in 2023-10, with the labels that each got.

#47 [FE] 게시판 Create, Read
  fe/package-lock.json
  fe/package.json
  fe/src/App.jsx
  fe/src/components/pages/BoardCreate.jsx
  fe/src/components/pages/BoardList.jsx
  fe/src/components/pages/BoardRead.css
  fe/src/components/pages/BoardRead.jsx
  fe/src/mockData/mockPosts.js
Labels: enhancement, FE

#52 [BE/FIX] : active on profile 설정 추가
  be/overflow/src/main/resources/application-dev-security.yml
  be/overflow/src/main/resources/application-local-security.yml
Labels: bug, BE👨‍💻

#55 [FEAT] access token 재발급
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/exception/AuthorizationException.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/service/CreateTokenService.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/LoginUserUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/ReissueUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/persistence/entity/AuthInfoEntity.java
  be/overflow/src/main/java/com/econovation/overflow/auth/persistence/entity/UserEntity.java
  be/overflow/src/main/java/com/econovation/overflow/auth/persistence/repository/AuthInfoRepository.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/AuthController.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/support/CookieExtractor.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/support/TokenExtractor.java
  be/overflow/src/main/java/com/econovation/overflow/security/token/TokenProvider.java
  be/overflow/src/main/java/com/econovation/overflow/security/token/TokenResolver.java
  be/overflow/src/main/java/com/econovation/overflow/security/token/TokenValidator.java
  be/overflow/src/main/resources/application-dev-security.yml
  be/overflow/src/main/resources/application-local-security.yml
  be/overflow/src/test/java/com/econovation/overflow/auth/domain/usecase/ReissueUseCaseTest.java
  be/overflow/src/test/java/com/econovation/overflow/auth/web/support/CookieExtractorTest.java
  be/overflow/src/test/java/com/econovation/overflow/security/token/TokenProviderTest.java
  be/overflow/src/test/java/com/econovation/overflow/security/token/TokenResolverTest.java
Labels: FEATURE, BE👨‍💻

#71 [BE] 인가 구현
  be/overflow/build.gradle
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/helper/Encoder.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/model/converter/UserModelConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/service/CreateTokenService.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/LoginUserUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/AuthInterceptor.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/support/AuthenticationPrincipalArgumentResolver.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/support/AuthorizationExtractor.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/support/Login.java
  be/overflow/src/main/java/com/econovation/overflow/config/PasswordEncode.java
  be/overflow/src/main/java/com/econovation/overflow/config/WebMvcConfig.java
  be/overflow/src/main/java/com/econovation/overflow/security/SecurityConfig.java
  be/overflow/src/main/java/com/econovation/overflow/security/authority/UserAuthority.java
  be/overflow/src/main/java/com/econovation/overflow/security/authority/UserRole.java
  be/overflow/src/main/java/com/econovation/overflow/security/token/TokenProvider.java
  be/overflow/src/main/java/com/econovation/overflow/security/token/TokenValidator.java
  be/overflow/src/test/java/com/econovation/overflow/auth/domain/usecase/SaveUserUseCaseTest.java
  be/overflow/src/test/java/com/econovation/overflow/security/token/TokenProviderTest.java
Labels: FEATURE, BE👨‍💻

#91 [Fix] security 의존성 제거로 인한 directory 위치 변경
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/service/CreateTokenService.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/ReissueUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/AuthInterceptor.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/support/AuthenticationPrincipalArgumentResolver.java
  be/overflow/src/main/java/com/econovation/overflow/config/WebMvcConfig.java
  be/overflow/src/main/java/com/econovation/overflow/support/token/NotValidToken.java
  be/overflow/src/main/java/com/econovation/overflow/support/token/TokenProvider.java
  be/overflow/src/main/java/com/econovation/overflow/support/token/TokenResolver.java
  be/overflow/src/main/java/com/econovation/overflow/support/token/TokenValidator.java
  be/overflow/src/main/resources/application-dev-security.yml
  be/overflow/src/test/java/com/econovation/overflow/support/token/TokenProviderTest.java
  be/overflow/src/test/java/com/econovation/overflow/support/token/TokenResolverTest.java
Labels: BE👨‍💻

#93 [Test] 로그인 business layer 테스트 코드
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/helper/Encoder.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/helper/EncoderImpl.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/service/GetAuthInfoService.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/ReissueUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/support/token/TokenResolver.java
  be/overflow/src/test/java/com/econovation/overflow/auth/domain/model/converter/UserModelConverterTest.java
  be/overflow/src/test/java/com/econovation/overflow/auth/domain/service/CreateTokenServiceTest.java
  be/overflow/src/test/java/com/econovation/overflow/auth/domain/service/GetAuthInfoServiceTest.java
  be/overflow/src/test/java/com/econovation/overflow/auth/domain/service/SaveTokenServiceTest.java
  be/overflow/src/test/java/com/econovation/overflow/auth/domain/usecase/LoginUserUseCaseTest.java
  be/overflow/src/test/java/com/econovation/overflow/auth/domain/usecase/ReissueUseCaseTest.java
  be/overflow/src/test/java/com/econovation/overflow/auth/domain/usecase/ValidEmailUseCaseTest.java
  be/overflow/src/test/java/com/econovation/overflow/auth/domain/usecase/ValidNicknameUseCaseTest.java
Labels: BE👨‍💻

#95 [Feat] health check api 구현
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/AuthController.java
  be/overflow/src/main/java/com/econovation/overflow/common/support/respnose/ApiResponseGenerator.java
  be/overflow/src/main/java/com/econovation/overflow/common/support/respnose/ApiResponseHeader.java
  be/overflow/src/main/java/com/econovation/overflow/health/HealthController.java
Labels: FEATURE, BE👨‍💻

#122 [INFRA] Dockerfile COPY path 수정
  be/overflow/Dockerfile
Labels: INFRA🌐

#123 [INFRA] Dockerfile COPY path 수정
  be/overflow/Dockerfile
Labels: INFRA🌐

#124 [INFRA] Dockerfile JAR_FILE path 수정
  be/overflow/Dockerfile
Labels: INFRA🌐

#125 [INFRA] Dockerfile JAR_FILE path 수정
  be/overflow/Dockerfile
Labels: INFRA🌐

#126 [INFRA] Dockerfile build app.jar 확인 코드 추가
  be/overflow/Dockerfile
Labels: INFRA🌐

#127 [INFRA] Dockerfile build app.jar 확인 코드 추가
  be/overflow/Dockerfile
Labels: INFRA🌐

#128 [INFRA] gralde.yml 내부 build jar working-directory path 추가
  .github/workflows/gradle.yml
  be/overflow/build.gradle
Labels: INFRA🌐

#130 [INFRA] gradle.yml gradle build run 수정
  .github/workflows/gradle.yml
  be/overflow/build.gradle
Labels: INFRA🌐

#131 [INFRA] Dockerfile run 커맨드 삭제
  be/overflow/Dockerfile
Labels: INFRA🌐

#133 [INFRA] gradle.yml docker build image name 추가
  .github/workflows/gradle.yml
Labels: INFRA🌐

#134 [INFRA] gradle.yml docker build image name 추가
  .github/workflows/gradle.yml
Labels: INFRA🌐

#136 [INFRA] gradle.yml docker push tag 추가
  .github/workflows/gradle.yml
Labels: INFRA🌐

#137 [INFRA] gradle.yml docker push tag 추가
  .github/workflows/gradle.yml
Labels: INFRA🌐

#138 [INFRA] gradle.yml docker build path 수정 및 태그 삭제
  .github/workflows/gradle.yml
Labels: INFRA🌐

#139 [INFRA] gradle.yml docker build path 수정 및 태그 삭제
  .github/workflows/gradle.yml
Labels: INFRA🌐

#141 [INFRA] ec2 user에게 docker dir 권한 부여
  .github/workflows/gradle.yml
Labels: INFRA🌐

#142 [INFRA] Deploy to dev working-directory path 추가
  .github/workflows/gradle.yml
Labels: INFRA🌐

#143 [INFRA] Deploy to dev working-directory path 추가
  .github/workflows/gradle.yml
Labels: INFRA🌐

#149 [INFRA] 최 상위 dir Dockerfile 삭제
  Dockerfile
Labels: INFRA🌐

#150 [INFRA] remove: gradle.yml 주석 삭제
  .github/workflows/gradle.yml
Labels: INFRA🌐

#152 [INFRA] feat: 인스턴스 시간 설정
  .github/workflows/gradle.yml
Labels: INFRA🌐

#153 [INFRA] 인스턴스 시간 설정
  .github/workflows/gradle.yml
Labels: INFRA🌐

#154 [INFRA] fix: 인스턴스 시간 재설정 2차
  .github/workflows/gradle.yml
Labels: INFRA🌐

#155 [INFRA] fix: 인스턴스 시간 재설정 2차
  .github/workflows/gradle.yml
Labels: INFRA🌐

#156 [INFRA] 인스턴스 시간 재설정 3차
  .github/workflows/gradle.yml
Labels: INFRA🌐

#157 [INFRA] 인스턴스 시간 재설정 3차
  .github/workflows/gradle.yml
Labels: INFRA🌐

#158 [INFRA] 인스턴스 시간 재설정 4차
  .github/workflows/gradle.yml
Labels: INFRA🌐

#159 [INFRA] 인스턴스 시간 재설정 4차
  .github/workflows/gradle.yml
Labels: INFRA🌐

#160 [INFRA] 인스턴스 시간 재설정 5차
  .github/workflows/gradle.yml
Labels: INFRA🌐

#161 [INFRA] 인스턴스 시간 재설정 5차
  .github/workflows/gradle.yml
Labels: INFRA🌐
