Repository JNU-econovation/econo-overflow, pull requests merged in 2023-09, with the labels that each got.

#21 feat/fe : 테일윈드 프레임워크 적용 - close #20
  .gitignore
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/manifest.json
  fe/src/.DS_Store
  fe/src/App.css
  fe/src/App.jsx
  fe/src/components/common/Footer.jsx
  fe/src/components/common/FooterContact.jsx
  fe/src/components/common/FooterIntro.jsx
  fe/src/components/common/FooterLink.jsx
  fe/src/components/common/FooterSite.jsx
  fe/src/components/common/Header.jsx
  fe/src/components/common/Loading.jsx
  fe/src/components/common/Nav.jsx
  fe/src/components/common/TitleLogo.jsx
  fe/src/components/common/common.css
  fe/src/components/login/LoginButton.jsx
  fe/src/components/login/LoginForm.jsx
  fe/src/components/login/LoginInput.jsx
  fe/src/components/login/LoginSuccess.jsx
  fe/src/components/login/LoginToSignup.jsx
  fe/src/components/login/login.css
  fe/src/components/main/Main.jsx
  fe/src/components/main/Search.jsx
  fe/src/components/main/main.css
  fe/src/components/main/main.html
  fe/src/components/signup/SignUpButton.jsx
  fe/src/components/signup/SignUpForm.jsx
  fe/src/components/signup/SignUpInput.jsx
  fe/src/components/signup/signup.css
  fe/src/index.css
  fe/src/index.jsx
  fe/tailwind.config.js
Labels: FE

#27 [BE] 프로젝트 공통 기능 구현
  be/overflow/src/main/java/com/ecnv/overflow/OverflowApplication.java
  be/overflow/src/main/java/com/econovation/overflow/common/BaseEntity.java
  be/overflow/src/main/java/com/econovation/overflow/common/SoftDeleteListener.java
  be/overflow/src/main/java/com/econovation/overflow/common/exception/BusinessException.java
  be/overflow/src/main/java/com/econovation/overflow/common/exception/GlobalExceptionHandler.java
  be/overflow/src/main/java/com/econovation/overflow/common/marker/AbstractDto.java
  be/overflow/src/main/java/com/econovation/overflow/common/marker/AbstractModel.java
  be/overflow/src/main/java/com/econovation/overflow/common/marker/AbstractRequestDto.java
  be/overflow/src/main/java/com/econovation/overflow/common/marker/AbstractResponseDto.java
  be/overflow/src/main/java/com/econovation/overflow/common/support/AbstractUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/common/support/converter/AbstractDtoConverter.java
  be/overflow/src/main/java/com/econovation/overflow/common/support/converter/AbstractEntityConverter.java
  be/overflow/src/main/java/com/econovation/overflow/common/support/respnose/ApiResponse.java
  be/overflow/src/main/java/com/econovation/overflow/common/support/respnose/ApiResponseBody.java
  be/overflow/src/main/java/com/econovation/overflow/common/support/respnose/ApiResponseGenerator.java
  be/overflow/src/main/java/com/econovation/overflow/common/support/respnose/MessageCode.java
  be/overflow/src/main/java/com/econovation/overflow/common/support/respnose/PageResponse.java
  be/overflow/src/main/java/com/econovation/overflow/config/MysqlConfig.java
  be/overflow/src/main/resources/application.properties
  be/overflow/src/test/java/com/ecnv/overflow/OverflowApplicationTests.java
Labels: FEATURE, BE👨‍💻

#28 [BE] 회원가입 기능 구현
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/exception/DuplicateException.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/model/UserModel.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/model/converter/UserModelConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/service/SaveUserService.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/SaveUserUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/ValidEmailUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/ValidNicknameUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/infra/converter/UserEntityConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/infra/entity/AuthInfoEntity.java
  be/overflow/src/main/java/com/econovation/overflow/auth/infra/entity/LoginType.java
  be/overflow/src/main/java/com/econovation/overflow/auth/infra/entity/UserEntity.java
  be/overflow/src/main/java/com/econovation/overflow/auth/infra/repository/UserRepository.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/SignUpController.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/ValidController.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/SaveUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/ValidEmailRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/ValidNicknameRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/supplier/EmailSupplier.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/supplier/NicknameSupplier.java
  be/overflow/src/main/java/com/econovation/overflow/common/annotation/SpecialLetter.java
  be/overflow/src/main/java/com/econovation/overflow/common/annotation/SpecialLetterValidator.java
  be/overflow/src/main/java/com/econovation/overflow/common/annotation/UpperCase.java
  be/overflow/src/main/java/com/econovation/overflow/common/annotation/UpperCaseValidator.java
  be/overflow/src/main/java/com/econovation/overflow/common/exception/GlobalExceptionHandler.java
  be/overflow/src/main/java/com/econovation/overflow/security/SecurityConfig.java
Labels: FEATURE, BE👨‍💻

#32 [FEAT] 로그인 기능 구현
  be/overflow/build.gradle
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/exception/NotFoundEmailException.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/exception/NotFoundPasswordException.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/service/SaveTokenService.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/LoginUserUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/SaveUserUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/ValidEmailUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/ValidNicknameUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/persistence/converter/AuthInfoEntityConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/persistence/converter/UserEntityConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/persistence/entity/AuthInfoEntity.java
  be/overflow/src/main/java/com/econovation/overflow/auth/persistence/entity/LoginType.java
  be/overflow/src/main/java/com/econovation/overflow/auth/persistence/entity/UserEntity.java
  be/overflow/src/main/java/com/econovation/overflow/auth/persistence/repository/AuthInfoRepository.java
  be/overflow/src/main/java/com/econovation/overflow/auth/persistence/repository/UserRepository.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/LoginController.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/converter/TokenConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/LoginUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/response/TokenResponse.java
  be/overflow/src/main/java/com/econovation/overflow/common/support/respnose/ApiResponse.java
  be/overflow/src/main/java/com/econovation/overflow/common/support/respnose/ApiResponseGenerator.java
  be/overflow/src/main/java/com/econovation/overflow/common/support/respnose/MessageCode.java
  be/overflow/src/main/java/com/econovation/overflow/security/authority/UserAuthority.java
  be/overflow/src/main/java/com/econovation/overflow/security/authority/UserRole.java
  be/overflow/src/main/java/com/econovation/overflow/security/exception/NotValidToken.java
  be/overflow/src/main/java/com/econovation/overflow/security/token/TokenProvider.java
  be/overflow/src/main/java/com/econovation/overflow/security/token/TokenResolver.java
  be/overflow/src/main/java/com/econovation/overflow/security/token/TokenValidator.java
  be/overflow/src/main/resources/application-local-security.yml
  be/overflow/src/main/resources/application.yml
Labels: FEATURE, BE👨‍💻

#37 [BE] 의존성 문제로 디렉터리 위치 변경
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/converter/TokenConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/request/LoginUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/request/SaveUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/request/ValidEmailRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/request/ValidNicknameRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/response/TokenResponse.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/model/converter/UserModelConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/LoginUserUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/SaveUserUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/LoginController.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/SignUpController.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/ValidController.java
Labels: BE👨‍💻

#38 [BE] 의존성 문제로 디렉터리 위치 변경 - Revert
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/converter/TokenConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/request/LoginUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/request/SaveUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/request/ValidEmailRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/request/ValidNicknameRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/response/TokenResponse.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/model/converter/UserModelConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/LoginUserUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/SaveUserUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/LoginController.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/SignUpController.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/ValidController.java
Labels: BE👨‍💻

#39 [BE] 의존성 문제로 디렉터리 위치 변경
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/converter/TokenConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/LoginUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/SaveUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/ValidEmailRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/ValidNicknameRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/response/TokenResponse.java
Labels: BE👨‍💻

#40 [Revert -BE] 의존성 문제로 디렉터리 위치 변경
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/converter/TokenConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/LoginUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/SaveUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/ValidEmailRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/ValidNicknameRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/response/TokenResponse.java
Labels: bug, BE👨‍💻

#41 [BE] revert로 인한 directory 위치 변경 이슈 해결
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/model/converter/UserModelConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/LoginUserUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/usecase/SaveUserUseCase.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/LoginController.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/SignUpController.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/controller/ValidController.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/converter/TokenConverter.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/LoginUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/SaveUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/ValidEmailRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/request/ValidNicknameRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/web/dto/response/TokenResponse.java
Labels: BE👨‍💻

#42 [FEAT] pre-commit시 lint 적용
  be/overflow/build.gradle
  be/overflow/scripts/pre-commit
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/request/LoginUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/request/SaveUserRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/request/ValidEmailRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/request/ValidNicknameRequest.java
  be/overflow/src/main/java/com/econovation/overflow/auth/domain/dto/response/TokenResponse.java
  be/overflow/tasks/install-git-hooks.gradle
Labels: FEATURE, BE👨‍💻
